studentName = input('Enter your name:')
studentNumber= int(input('Enter your student number:'))
studentAge = int(input('Enter your age:'))
courseName = input('Enter your course name:')
programmingMark = int(input('Enter your programming mark:'))
databaseMark = int(input('Enter your database mark:'))
webDevelopmentMark = int(input('Enter your web development mark:'))

print(f'Student Name : {studentName}')
print(f'Student Number: {studentNumber}')
print(f'Student Age : {studentAge}')
print(f'Course Name : {courseName}')
print(f'Programming Mark : {programmingMark}')
print(f'Database Mark : {databaseMark}')
print(f'Web Development Mark : {webDevelopmentMark}')
